
focused_opacity=1.0
unfocused_opacity=0.95

blur=1
blur_optimized=1

gappih=10
gappiv=10
gappoh=10
gappov=10

border_radius=0
tag_num=10
circle_layout=dwindle,scroller
cursor_theme=MacOS-Tahoe-Cursor

animations=1
layer_animations=0
animation_type_open=slide
animation_type_close=slide
animation_duration_workspace = 0

borderpx=2
cursor_size=24
